language: node_js
node_js:
  - "stable"
dist: focal

install:
  - npm install

script:
  - npm test
  - npm run build

before_deploy:
  - gem update --system
  - gem install bundler
  - gem install uri -v 1.0.2
  - gem install faraday
  - gem install faraday-net_http

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: main
