language: node_js
node_js:
  - "stable"
dist: focal

before_script:
  - cd $TRAVIS_BUILD_DIR

script:
  - npm install
  - npm test

before_deploy:
  - gem update --system
  - gem install bundler
  - gem install uri -v 1.0.2

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: main
