language: node_js
node_js:
  - "18"
dist: focal
cache:
  directories:
    - node_modules

before_install:
  - gem install bundler


deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: main
before_deploy:
  - npm run build
